routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

// use Symfony\Component\Routing\Annotation\Route;

Route::get('/Admin', function () {
    return view('login');
});

//front end
Route::get('/', 'Web\FrontController@index');
Route::get('/About', 'Web\FrontController@about')->name('about');
Route::get('/Contact', 'Web\FrontController@contact')->name('contact');
Route::get('/Artikel/{artikel}', 'Web\FrontController@show')->name('artikel.detail');
Route::get('/Artikel-kategori{kategori}', 'Web\FrontController@artikel_kategori')->name('artikel.kategori');

Auth::routes();

//back end (Admin)
Route::group(['middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categori', 'CategoriController');
    Route::resource('artikel', 'ArtikelController'); 
});

app/Artikel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Categori;

class Artikel extends Model
{
    protected $table="table_artikels";
    protected $fillabel= ['judul', 'slug'];
    protected $guarded=['id'];


    public function Kategori()
    {
        return $this->belongsTo(\App\Categori::class,'categoris_id','id');
    }


    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/ArtikelController.php
<?php
namespace App\Http\Controllers;
use Storage;
use Illuminate\Http\Request;
use App\Artikel;
use App\Categori;
class ArtikelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $artikel = Artikel::latest()->get();
        return view('artikel.index', compact('artikel'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categori = Categori::select('id', 'nama_kategori')->get();
        return view('artikel.create', compact('categori'));

    }
    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'judul' => 'required',
            'body' => 'required|min:10',
            'gambar' => 'mimes:jpeg,bmp,png',
        ]);
    

        if (empty($request->file('gambar'))) {
            Artikel::create([
                'judul' => $request->judul,
                'slug' => \Str::slug($request->judul),
                'body' => $request->body,
                //'gambar' => $image,
                'categoris_id' => $request->categoris_id,
            ]);
        } else {
            Artikel::create([
                'judul' => $request->judul,
                'slug' => \Str::slug($request->judul),
                'body' => $request->body,
                'gambar' => $request->file('gambar')->store('artikel'),
                'categoris_id' => $request->categoris_id,
            ]);
        }
        return redirect()->route('artikel.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $categori = Categori::select('id', 'nama_kategori')->get();
        $artikel = Artikel::find($id);
        return view('artikel.edit', compact('categori', 'artikel'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'judul' => 'required',
            'body' => 'required|min:10',
            'gambar' => 'mimes:jpeg,bmp,png',
        ]);
        if (empty($request->file('gambar'))) {
            $artikel = Artikel::find($id);
            //Storage::delete($artikel->gambar);
            $artikel->update([
                'judul' => $request->judul,
                'slug' => \Str::slug($request->judul),
                'body' => $request->body,
                //'gambar' => $request->file('gambar')->store('artikel'),
                'categoris_id' => $request->categoris_id,
            ]);
        } else {
            $artikel = Artikel::find($id);
            Storage::delete($artikel->gambar);
            $artikel->update([
                'judul' => $request->judul,
                'slug' => \Str::slug($request->judul),
                'body' => $request->body,
                'gambar' => $request->file('gambar')->store('artikel'),
                'categoris_id' => $request->categoris_id,
            ]);
        }
        return redirect()->route('artikel.index');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $artikel = Artikel::find($id);
        if (!$artikel) {
            return redirect()->back();
        }
        Storage::delete($artikel->gambar);
        $artikel->delete();
        return redirect()->route('artikel.index');
    }
}

resources/views/artikel/create.blade.php
@extends('layouts.app')
  @push('customcss')
  <link rel="stylesheet" href="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">
  @endpush
  @section('title','Dashboard')
  @section('page-title','Home')
  @section('content')
  <!-- Default box -->
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Tambah Artikel Baru

      </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body pad">
      <form action="{{ route('artikel.store') }}" enctype="multipart/form-data" method="POST">
        @csrf
        <div class="form-group">
            @if($errors->has('judul'))
              <div class="alert alert-danger">
                  <strong>{{ $errors->first('judul') }}</strong>
              </div>
            @endif
          <label>Judul Artikel</label>
          <input type="text" class="form-control" required name="judul">
        </div>
        <div class="form-group">
            @if($errors->has('gambar'))
              <div class="alert alert-danger">
                  <strong>{{ $errors->first('gambar') }}</strong>
              </div>
            @endif
          <label>Gambar</label>
          <input type="file" class="form-control" required name="gambar">
        </div>
        <div class="form-group">
          <label>Kategori Artikel</label>
          <select required name="categoris_id" class="form-control">
              @foreach ($categori as $item)
                <option value={{$item->id}}>{{$item->nama_kategori}}</option>
              @endforeach
          </select>
        </div>
        <div class="form-group">
          <label>Isi Artikel</label>
            @if($errors->has('body'))
              <div class="alert alert-danger">
                  <strong>{{ $errors->first('body') }}</strong>
              </div>
            @endif
           <textarea  required name="body" id="editor1" class="textarea" placeholder="Place some text here"
                style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">
          </textarea>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Tambah Artikel</button>
          <a href="{{ route('artikel.index') }}" class="btn btn-danger">Kembali</a>
        </div>

      </form>
    </div>
  </div>
</div>
  <!-- /.box -->
  @endsection
  @push('datatables')
  <!-- Bootstrap WYSIHTML5 -->
  <script src="{{asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
  <script>
    $(function () {
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      //CKEDITOR.replace('editor1')
      //bootstrap WYSIHTML5 - text editor
      $('.textarea').wysihtml5()
    })
  </script>
  @endpush

resources/views/artikel/edit.blade.php
@extends('layouts.app')
  @push('customcss')
  <link rel="stylesheet" href="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">
  @endpush
  @section('title','Dashboard')
  @section('page-title','Edit Artikel')
  @section('content')
  <!-- Default box -->
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Edit Artikel

      </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body pad">
      <form action="{{ route('artikel.update',$artikel->id) }}" enctype="multipart/form-data" method="POST">
        @csrf

        @method('PUT')
        <div class="form-group">
          <label>Judul Artikel</label>
          <input type="text" class="form-control" name="judul" value="{{$artikel->judul}}">
        </div>
        <div class="form-group">
          <label>Gambar</label>
          <input type="file" class="form-control" name="gambar">
        </div>
        <div class="form-group">
          <label>Kategori Artikel</label>
          <select name="categoris_id" class="form-control">
              @foreach ($categori as $item)

                @if($item->id==$artikel->categoris_id)

                <option value={{$item->id}} selected >{{$item->nama_kategori}}</option>

                @else

                <option value={{$item->id}}>{{$item->nama_kategori}}</option>

                @endif
              @endforeach
          </select>
        </div>
        <div class="form-group">
          <label>Isi Artikel</label>
           <textarea name="body" id="editor1" class="textarea" placeholder="Place some text here"
                style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">

                {!! $artikel->body !!}

          </textarea>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Edit Artikel</button>
          <a href="{{ route('artikel.index') }}" class="btn btn-danger">Kembali</a>
        </div>

      </form>
    </div>
  </div>
</div>
  <!-- /.box -->
  @endsection
  @push('datatables')
  <!-- Bootstrap WYSIHTML5 -->
  <script src="{{asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
  <script>
    $(function () {
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      //CKEDITOR.replace('editor1')
      //bootstrap WYSIHTML5 - text editor
      $('.textarea').wysihtml5()
    })
  </script>
  @endpush

resources/views/artikel/index.blade.php
@extends('layouts.app')
@push('customcss')
<script src="{{ asset('plugins/datatables/dataTables.bootstrap.css') }}"></script>
@endpush
  @section('title','Dashboard')
  @section('page-title','Artikel')
  @section('content')
  <!-- Default box -->
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Data Artikel</h3>
      <div class="pull-right">
          <a href="{{ route('artikel.create') }}" class="btn btn-success">Tambah Artikel</a>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table id="myTable" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>No</th>
          <th>Judul</th>
          <th>Gambar</th>
          <th>Nama Kategori</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          @foreach ($artikel as $item)
          <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$item->judul}}</td>
                    
                    @if($item->gambar==null)
                    <td>Gambar tidak ada</td>
                    @else
                    <td><img src="{{ asset('uploads/'.$item->gambar) }}" width="50px" height="50px" ></td>
                    @endif

                    <td>{{$item->Kategori->nama_kategori}}</td>
                    <td>
                        <a href="{{ route('artikel.edit',$item->id) }}" class="btn btn-info">Edit</a>
                        
                        <a href="javascript:void(0)" onclick="$(this).find('form').submit()" class="btn btn-danger">
                                <span class="fa fa-trash"></span>
                                <form action="{{ route('artikel.destroy', $item->id) }}" method="POST">
                                     @csrf

                                     @method('DELETE')
                                </form>

                        </a>
                    </td>
                </tr>
          @endforeach
             
        </tbody>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
  @push('datatables')

  <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables/datatables.bootstrap.min.js') }}"></script>
  @endpush
  @push('customdatatables')
  <script>
    $(document).ready( function () {
    $('#myTable').DataTable();
    
    } );
  </script>
<!-- alert sweetAlert -->
 <!-- <script>
   $('.delete').click(function(){
    swal({
      title: "Yakin ?",
      text: "Mau dihapus data artikel ini!",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        swal("Poof! Your imaginary file has been deleted!", {
          icon: "success",
        });
      } else {
        swal("Your imaginary file is safe!");
      }
    });
   });
 </script> -->
  @endpush
  @endsection