routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

// use Symfony\Component\Routing\Annotation\Route;

Route::get('/Admin', function () {
    return view('login');
});

//front end
Route::get('/', 'Web\FrontController@index');
Route::get('/About', 'Web\FrontController@about')->name('about');
Route::get('/Contact', 'Web\FrontController@contact')->name('contact');
Route::get('/Artikel/{artikel}', 'Web\FrontController@show')->name('artikel.detail');
Route::get('/Artikel-kategori{kategori}', 'Web\FrontController@artikel_kategori')->name('artikel.kategori');

Auth::routes();

//back end (Admin)
Route::group(['middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categori', 'CategoriController');
    Route::resource('artikel', 'ArtikelController'); 
});

app/Http/Controllers/Web/FrontController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Categori;
use App\Artikel;

class FrontController extends Controller
{
    public function index()
    {

        $categori = Categori::all();

        $artikel = Artikel::latest()->get()->random(2);

        $artikelall = Artikel::latest()->get();
        $artikelterkait = Artikel::latest()->limit(4)->get();

        return view('front',compact('categori','artikel','artikelall','artikelterkait'));
    }

    public function show(Artikel $artikel)
    {
        // var_dump('hahaha');
        // die;
        // $artikel_detail = $artikel;
        // dd($artikel);

        
        $artikelterkait = Artikel::latest()->get()->random(3);
        $categori = Categori::withCount('Artikel')->get();

       
    
        return view ('front.artikel_detail',compact('artikel','categori','artikelterkait'));
    }

    public function artikel_kategori(Categori $kategori)
    {
        $categori = Categori::all();

        $artikel = Artikel::latest()->get()->random(2);

        $artikelall = $kategori->Artikel()->get();
        $artikelterkait = Artikel::latest()->limit(4)->get();

        return view('front',compact('categori','artikel','artikelall','artikelterkait'));

        return $artikelall;
    }

    public function about()
    {
        $categori = Categori::all();

        return view ('front.about', compact('categori'));
    }

    public function contact()
    {
        $categori = Categori::all();

        return view ('front.contact', compact('categori'));
    }

}

resources/views/front/about.blade.php
@extends('template.app')
@section('content')
@push('nav')
    <ul class="nav-menu nav navbar-nav">
        @foreach ($categori as $item)
            <li class="cat-4"><a href="{{ route('artikel.kategori',$item->slug) }}">{{$item->nama_kategori}}</a></li>
        @endforeach

    </ul>
@endpush
    <!-- Page Header -->
		<div class="page-header">
			<div class="container">
				<div class="row">
					<div class="col-md-10">
						<ul class="page-header-breadcrumb">
							<li><a href="/">Home</a></li>
							<li>About Us</li>
						</ul>
					<h1>About Us</h1>
				</div>
			</div>
		</div>
	</div>
<!-- /Page Header -->
	
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<div class="col-md-8">
					<div class="section-row">
						<p>Lorem ipsum dolor sit amet, ea eos tibique expetendis, tollit viderer ne nam. No ponderum accommodare
							eam, purto nominavi cum ea, sit no dolores tractatos. Scripta principes quaerendum ex has, ea mei omnes
							eruditi. Nec ex nulla mandamus, quot omnesque mel et. Amet habemus ancillae id eum, justo dignissim mei
							ea, vix ei tantas aliquid. Cu laudem impetus conclusionemque nec, velit erant persius te mel. Ut eum
							verterem perpetua scribentur.</p>
						<figure class="figure-img">
							<img class="img-responsive" src="./img/about-1.jpg" alt="">
						</figure>
						<p>Vix mollis admodum ei, vis legimus voluptatum ut, vis reprimique efficiendi sadipscing ut. Eam ex animal
							assueverit consectetuer, et nominati maluisset repudiare nec. Rebum aperiam vis ne, ex summo aliquando
							dissentiunt vim. Quo ut cibo docendi. Suscipit indoctum ne quo, ne solet offendit hendrerit nec. Case
							malorum evertitur ei vel.</p>
					</div>
					<div class="row section-row">
						<div class="col-md-6">
							<figure class="figure-img">
								<img class="img-responsive" src="./img/about-2.jpg" alt="">
							</figure>
						</div>
						<div class="col-md-6">
							<h3>Our Mission</h3>
							<p>Id usu mutat debet tempor, fugit omnesque posidonium nec ei. An assum labitur ocurreret qui, eam
								aliquid ornatus tibique ut.</p>
							<ul class="list-style">
								<li>
									<p>Vix mollis admodum ei, vis legimus voluptatum ut.</p>
								</li>
								<li>
									<p>Cu cum alia vide malis. Vel aliquid facilis adolescens.</p>
								</li>
								<li>
									<p>Laudem rationibus vim id. Te per illum ornatus.</p>
								</li>
							</ul>
						</div>
					</div>
				</div>

				
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
    <!-- /section -->
@push('categoris')
    <ul class="footer-links">
        @foreach ($categori as $item)
        <li><a href="{{ route('artikel.kategori',$item->slug) }}">{{$item->nama_kategori}}</a></li>
        
        @endforeach
    </ul>
@endpush
@endsection

resources/views/front/artikel_detail.blade.php
@extends('template.app')
@section('content')

<!-- section -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- Post content -->
            <div class="col-md-8">
                <div class="section-row sticky-container">
                    <div class="main-post">
                        <h3>{{$artikel->judul}}</h3>
                        <figure class="figure-img">
                            <img class="img-responsive" src="{{ asset('uploads/'.$artikel->gambar) }}" alt="">
                        </figure>

                        {!! $artikel->body !!}

                    </div>
                    <div class="post-shares sticky-shares">
                        <a href="#" class="share-facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="share-twitter"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="share-google-plus"><i class="fa fa-google-plus"></i></a>
                        <a href="#" class="share-pinterest"><i class="fa fa-pinterest"></i></a>
                        <a href="#" class="share-linkedin"><i class="fa fa-linkedin"></i></a>
                        <a href="#"><i class="fa fa-envelope"></i></a>
                    </div>
                </div>
               
            </div>
            <!-- /Post content -->

            <!-- aside -->
            <div class="col-md-4">
                <!-- post widget -->
                <div class="aside-widget">
                    <div class="section-title">
                        <h2>Featured Posts</h2>
                    </div>

                    @foreach ($artikelterkait as $item)
                        <div class="post post-thumb">
                            <a class="post-img" href="#">
                                <img src="{{ asset('uploads/'.$item->gambar) }}" width="200px" height="200px" alt=""></a>
                            <div class="post-body">
                                <div class="post-meta">
                                    <a class="post-category cat-3" href="#">{{$item->kategori->nama_kategori}}</a>
                                    <span class="post-date">{{$item->created_at->diffForHumans()}}</span>
                                </div>
                                <h3 class="post-title">
                                    <a href="{{ route('artikel.detail', $item->slug) }}">
                                        {{$item->judul}}
                                    </a>
                                </h3>
                            </div>
                        </div>

                    @endforeach
                </div>
                <!-- /post widget -->

                <!-- catagories -->
                <div class="aside-widget">
                    <div class="section-title">
                        <h2>Catagories</h2>
                    </div>
                    <div class="category-widget">
                        <ul>
                            @foreach ($categori as $c)
                                <li><a href="{{ route('artikel.kategori',$c->slug) }}" class="cat-1">{{$c->nama_kategori}}<span>{{$c->artikel_count}}</span></a></li>
                            @endforeach
                          
                        </ul>
                    </div>
                </div>
                <!-- /catagories -->
            </div>
            <!-- /aside -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /section -->

@push('categoris')
    <ul class="footer-links">
        @foreach ($categori as $item)
        <li><a href="{{ route('artikel.kategori',$item->slug) }}">{{$item->nama_kategori}}</a></li>
        
        @endforeach
    </ul>

@endpush

@endsection

resources/views/front/contact.blade.php
@extends('template.app')
@section('content')
@push('nav')
    <ul class="nav-menu nav navbar-nav">
        @foreach ($categori as $item)
            <li class="cat-4"><a href="{{ route('artikel.kategori',$item->slug) }}">{{$item->nama_kategori}}</a></li>
        @endforeach

    </ul>
@endpush

<!-- Page Header -->
<div class="page-header">
				<div class="container">
					<div class="row">
						<div class="col-md-10">
							<ul class="page-header-breadcrumb">
								<li><a href="/">Home</a></li>
								<li>Contact</li>
							</ul>
							<h1>Contact</h1>
						</div>
					</div>
				</div>
			</div>
			<!-- /Page Header -->

<!-- section -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-6">
						<div class="section-row">
							<h3>Contact Information</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
							<ul class="list-style">
								<li><p><strong>Email:</strong> <a href="#"><span class="__cf_email__" data-cfemail="93c4f6f1fef2f4d3f6fef2faffbdf0fcfe">ilhamarifin.official@gmail.com</span></a></p></li>
								<li><p><strong>Phone:</strong> 0857 9869 2347</p></li>
								<li><p><strong>Address:</strong> Jl.Sirnasari Sirnasari Babakanjambu RT. 025 RW. 009 Sirnasari Kab. Sukabumi</p></li>
							</ul>
						</div>
					</div>
					<div class="col-md-5 col-md-offset-1">
						<div class="section-row">
							<h3>Send A Message</h3>
							<form>
								<div class="row">
									<div class="col-md-7">
										<div class="form-group">
											<span>Email</span>
											<input class="input" type="email" name="email">
										</div>
									</div>
									<div class="col-md-7">
										<div class="form-group">
											<span>Subject</span>
											<input class="input" type="text" name="subject">
										</div>
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<textarea class="input" name="message" placeholder="Message"></textarea>
										</div>
										<button class="primary-button">Submit</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
        <!-- /section -->
@push('categoris')
    <ul class="footer-links">
        @foreach ($categori as $item)
        <li><a href="{{ route('artikel.kategori',$item->slug) }}">{{$item->nama_kategori}}</a></li>
        
        @endforeach
    </ul>
@endpush
@endsection