routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

// use Symfony\Component\Routing\Annotation\Route;

Route::get('/Admin', function () {
    return view('login');
});

//front end
Route::get('/', 'Web\FrontController@index');
Route::get('/About', 'Web\FrontController@about')->name('about');
Route::get('/Contact', 'Web\FrontController@contact')->name('contact');
Route::get('/Artikel/{artikel}', 'Web\FrontController@show')->name('artikel.detail');
Route::get('/Artikel-kategori{kategori}', 'Web\FrontController@artikel_kategori')->name('artikel.kategori');

Auth::routes();

//back end (Admin)
Route::group(['middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categori', 'CategoriController');
    Route::resource('artikel', 'ArtikelController'); 
});

app/Categori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

use App\Artikel;

class Categori extends Model
{
    protected $table ='table_categoris';
    protected $guarded =['id'];
    
    // protected $fillable = [
    //     'nama_kategori', 'slug', 
    //     ];


    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug($value);
    }


    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function Artikel()
    {
        return $this->hasMany(\App\Artikel::class,'categoris_id','id');
    }
}
 

app/Http/Controllers/CategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Categori;

class CategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $categori = Categori::all();
        $categori = Categori::latest()->get();
        return view('categori.index', compact('categori'));
    }

    public function create()
    {
        return view('categori.create');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'nama_kategori'=>'required|min:3',
        ]);

        Categori::create([
            'nama_kategori' => $request->nama_kategori,
            'slug' => \Str::slug($request->nama_kategori),
        ]);

        return redirect()->route('categori.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $categori = Categori::find($id);

        return view('categori.edit',compact('categori'));
    }

    public function update(Request $request, $id)
    {
        $categori = Categori::find($id);

        // $nama_kategori = $request->nama_kategori;
        // $slug = \Str::slug($request->nama_kategori);

        // var_dump($nama_kategori);
        // dd($slug);

        // $categori->update($request->all());

        $categori->update([
            'nama_kategori' => $request->nama_kategori,
            'slug' => \Str::slug($request->nama_kategori),
        ]);

        return redirect()->route('categori.index');
    }

    public function destroy($id)
    {
        
        $categori = Categori::find($id);

        if (!$categori){
            return redirect()->back();
        }

        $categori->delete();
        return redirect()->route('categori.index');
    }
}

resources/views/categori/create.blade.php
@extends('layouts.app')
  @section('title','Dahsboard')
  @section('page-title','Home')
  @section('content')
  <div class="row">
    <!-- left column -->
    <div class="col-md-8">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Kategori</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form action="{{ route('categori.store') }}" method="POST">
        @csrf
          <div class="box-body">
            <div class="form-group">
                @if($errors->has('nama_kategori'))
                    <div class="alert alert-danger">
                      <strong>{{ $errors->first('nama_kategori') }}</strong>
                    </div>
                @endif

              <label for="exampleInputEmail1">Nama Kategori</label>
              <input type="text" required class="form-control" name="nama_kategori" placeholder="Kategori"  value="{{ old('nama_kategori') }}">
            </div>
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-primary">Tambah Kategori</button>
            <a href="{{ route('categori.index') }}" class="btn btn-danger">Kembali</a>
            <!-- <button type="submit" class="btn btn-danger">Kembali</button> -->

          </div>
        </form>
      </div>
    </div>
  </div>
      <!-- /.box -->

  @endsection

resources/views/categori/edit.blade.php
@extends('layouts.app')
  @section('title','Dahsboard')
  @section('page-title','Edit')
  @section('content')
  <div class="row">
    <!-- left column -->
    <div class="col-md-8">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit Kategori</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form action="{{ route('categori.update',$categori->id) }}" method="POST">
        @method('PUT')
        @csrf
          <div class="box-body">
            <div class="form-group">
              <label for="exampleInputEmail1">Nama Kategori</label>
              <input type="text" class="form-control" name="nama_kategori" placeholder="Kategori"  value="{{ $categori->nama_kategori }}">
            </div>
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-primary">Edit</button>
            <a href="{{ route('categori.index') }}" class="btn btn-danger">Kembali</a>
            <!-- <button type="submit" class="btn btn-danger">Kembali</button> -->

          </div>
        </form>
      </div>
    </div>
  </div>
      <!-- /.box -->

  @endsection

resources/views/categori/index.blade.php
@extends('layouts.app')
@push('customcss')
<script src="{{ asset('plugins/datatables/dataTables.bootstrap.css') }}"></script>
@endpush
  @section('title','Dashboard')
  @section('page-title','Categori')
  @section('content')
  <!-- Default box -->
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Data Categori</h3>
      <div class="pull-right">
       <a href="{{ route('categori.create') }}" class="btn btn-success">Tambah Kategori</a>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table id="myTable1" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>No</th>
          <th>Nama Kategori</th>
          <th>Slug</th>
          <th>Aksi</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($categori as $item)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>
                        {{$item->nama_kategori}}
                    </td>
                    <td>{{$item->slug}}</td>
                    <td>
                        <a href="{{ route('categori.edit', $item->id) }}" class="btn btn-info">Edit</a>
                        
                        <a href="javascript:void(0)" onclick="$(this).find('form').submit()" class="btn btn-danger">
                            <span class="fa fa-trash"></span>
                            <form action="{{ route('categori.destroy', $item->id) }}" method="POST">

                            @csrf
                            @method('DELETE')

                            </form>
                        
                        </a>
                    </td>
                </tr>
            @endforeach
      
        </tbody>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
  @push('datatables')
  <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables/datatables.bootstrap.min.js') }}"></script>
  @endpush
  @push('customdatatables')
  <script>
     $(document).ready( function () {
    $('#myTable1').DataTable();
    
    } );
  </script>
  @endpush
  @endsection